<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>m78-netdisk</artifactId>
        <groupId>com.m78</groupId>
        <version>1.0.0</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <artifactId>netdisk-bootstrap</artifactId>

    <dependencies>
        <dependency>
            <groupId>com.m78</groupId>
            <artifactId>netdisk-common</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.m78</groupId>
            <artifactId>netdisk-user</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.m78</groupId>
            <artifactId>netdisk-file</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.m78</groupId>
            <artifactId>netdisk-album</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>com.m78</groupId>
            <artifactId>netdisk-share</artifactId>
            <version>1.0.0</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- mysql-->
        <dependency>
            <groupId>com.mysql</groupId>
            <artifactId>mysql-connector-j</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
        <dependency>
            <groupId>com.m78</groupId>
            <artifactId>netdisk-vault</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.m78</groupId>
            <artifactId>netdisk-calendar</artifactId>
            <version>${project.version}</version>
        </dependency>
        <dependency>
            <groupId>com.h2database</groupId>
            <artifactId>h2</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <finalName>m78-netdisk</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>